### ISSUE TITLE
Add: chassignore file

### ISSUE THREAD

**Issue by dpaez** [geut/chaas#5]
It should be used to indicate what files must be ignored from a changelog change check, e.g.: usually, a change on a readme file does not need to be on the changelog.

**Comment by elmasse** [comment]
I'm gonna add a .chaas.yaml or chaas.config.js for configuring the service. The ignore will be handled in the config file.

**Comment by dpaez** [comment]
Super cool

https://bukk.it/dubdubdub.gif
